//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Core.Metadata.Edm;
using Microsoft.AspNet.Identity.EntityFramework;

namespace KYHBPA.Entity
{
    using System;
    using System.Collections.Generic;

    //[Table("Roles", Schema = "Identity")]
    public partial class Role : IdentityRole<Guid, UserRole>
    {
        private readonly ICollection<UserRole> _users;

        public Role()
        {
            this._users = new HashSet<UserRole>();
        }

        [InverseProperty("Role")]
        public override ICollection<UserRole> Users
        {
            get { return _users; }
        }
    }
}
