//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNet.Identity.EntityFramework;

namespace KYHBPA.Entity
{
    using System;
    using System.Collections.Generic;

    [Table("UserClaims", Schema = "Identity")]
    public partial class UserClaim : IdentityUserClaim<Guid>
    {        
        [ForeignKey(nameof(User))]
        public override Guid UserId { get; set; }

        //[InverseProperty("Claims")]
        public virtual ApplicationUser User { get; set; }
    }
}
