//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNet.Identity.EntityFramework;

namespace KYHBPA.Entity
{
    using System;
    using System.Collections.Generic;

    [Table("UserLogins", Schema = "Identity")]
    public partial class UserLogin : IdentityUserLogin<Guid>
    {
        [Key, Required]
        [Column(Order = 0)]
        public override string LoginProvider { get; set; }
        [Key, Required]
        [Column(Order = 1)]
        public override string ProviderKey { get; set; }
        [Key, Required]
        [Column(Order = 2)]
        [ForeignKey(nameof(User))]
        public override Guid UserId { get; set; }

        //[InverseProperty("Logins")]
        public virtual ApplicationUser User { get; set; }
    }
}
