USE CIS31026
IF SCHEMA_ID('DW') IS NULL EXEC('CREATE SCHEMA DW')
ALTER USER CIS31026 WITH DEFAULT_SCHEMA = [DW]
IF OBJECT_ID('DW.Fact', 'U') IS NOT NULL DROP TABLE [DW].[Fact]; 
IF OBJECT_ID('DW.PilotDimension', 'U') IS NOT NULL DROP TABLE [DW].[PilotDimension]
IF OBJECT_ID('DW.ModelDimension', 'U') IS NOT NULL DROP TABLE [DW].[ModelDimension]
IF OBJECT_ID('DW.TimeDimension', 'U') IS NOT NULL DROP TABLE [DW].[TimeDimension] 
IF OBJECT_ID('DW.STAGING', 'U') IS NOT NULL DROP TABLE [DW].[STAGING] 


CREATE TABLE [DW].[PilotDimension](
PilotID INT IDENTITY NOT NULL,
EMP_NUM INT NULL,
EMP_LNAME VARCHAR(15) NULL,
EMP_FNAME VARCHAR(15) NULL,
PIL_LICENSE VARCHAR(25) NULL,
PIL_RATINGS VARCHAR(25) NULL,
PIL_MED_TYPE VARCHAR(1) NULL,
PIL_MED_DATE DATETIME NULL,
PIL_PT135_DATE DATETIME NULL,
);

CREATE TABLE [DW].[ModelDimension](
ModelID INT IDENTITY NOT NULL,
MOD_CODE VARCHAR(10) NULL,
MOD_MANUFACTURER VARCHAR(15) NULL,
MOD_NAME VARCHAR(20) NULL,
MOD_SEATS FLOAT(8) NULL,
MOD_CHG_MILE FLOAT(8) NULL,
);

CREATE TABLE [DW].[TimeDimension](
TimeID INT IDENTITY NOT NULL,
CHAR_DATE DATE NULL,
CHAR_YEAR INT NULL,
CHAR_MONTH INT NULL,
);

CREATE TABLE [DW].[Fact](
PilotID INT NOT NULL,
ModelID INT NOT NULL,
TimeID INT NOT NULL,
CHAR_FUEL_GALLONS FLOAT(8) NULL,
CHAR_DISTANCE FLOAT(8) NULL,
REVENUE DECIMAL(6,2) NULL,
);

ALTER TABLE [DW].[PilotDimension]
	ADD CONSTRAINT PK_PILOTDIMENSION PRIMARY KEY(PilotID);
ALTER TABLE [DW].[ModelDimension]
	ADD CONSTRAINT PK_MODELDIMENSION PRIMARY KEY(ModelID);
ALTER TABLE [DW].[TimeDimension]
	ADD CONSTRAINT PK_TIMEDIMENSION PRIMARY KEY(TimeID);

ALTER TABLE [DW].[Fact] ADD
	CONSTRAINT PK_FACT PRIMARY KEY (PilotID, ModelID, TimeID),
	CONSTRAINT FK_FACT_PILOT FOREIGN KEY (PilotID) REFERENCES [DW].[PilotDimension](PilotID),
	CONSTRAINT FK_FACT_MODEL FOREIGN KEY (ModelID) REFERENCES [DW].[ModelDimension](ModelID),
	CONSTRAINT FK_FACT_TIME FOREIGN KEY (TimeID) REFERENCES [DW].[TimeDimension](TimeID);


CREATE TABLE [DW].[STAGING](
PilotID INT NULL,
ModelID INT NULL,
TimeID INT NULL,
EMP_NUM INT NULL,
MOD_CODE VARCHAR(10) NULL,
CHAR_DATE DATETIME NULL,
CHAR_DISTANCE FLOAT(8) NULL,
CHAR_FUEL_GALLONS FLOAT(8) NULL,
REVENUE DECIMAL(6,2) NULL,
);