--Louis Ries, CIS310-01 Assignment 8
--1
SELECT ItemID, Description, ListPrice from PET..Merchandise where ListPrice > (SELECT AVG(LISTPRICE) FROM PET..MERCHANDISE)
--2
SELECT M.ITEMID, AVG(O.COST) AS "Average Cost", AVG(S.SALEPRICE) AS "Average Sale Price"
FROM PET..MERCHANDISE M INNER JOIN PET..SALEITEM S ON M.ITEMID = S.ITEMID 
INNER JOIN PET..ORDERITEM O ON M.ITEMID = O.ITEMID 
group by M.ITEMID HAVING AVG(S.SALEPRICE) > (1.5*avg(O.COST))
--3
SELECT  E.EMPLOYEEID, E.LASTNAME, 
sum(si.quantity * si.saleprice) AS "TOTALSALES", 
FORMAT(SUM(si.Quantity*si.SalePrice)/(SELECT SUM(QUANTITY*SALEPRICE) FROM PET..SALEITEM),'P') AS "PCTSALES"
FROM PET..EMPLOYEE E INNER JOIN PET..SALE S ON E.EMPLOYEEID = S.EmployeeID
INNER JOIN PET..SaleItem SI ON S.SALEID = SI.SALEID
GROUP BY E.EmployeeID, E.LastName
--4
SELECT TOP 1 S.SUPPLIERID, S.NAME, FORMAT(SUM(M.SHIPPINGCOST)/(SELECT SUM(SHIPPINGCOST) FROM PET..MERCHANDISEORDER),'P') AS PCTSHIPCOST
FROM PET..SUPPLIER S INNER JOIN PET..MerchandiseOrder M ON S.SUPPLIERID = M.SupplierID
GROUP BY S.SupplierID, S.Name
ORDER BY PCTSHIPCOST DESC
--5
SELECT TOP 1 Q.*, (Q.MERCTOTAL+Q.ANIMALTOTAL) AS "GrandTotal" FROM 
(SELECT C.CUSTOMERID, C.LASTNAME, C.FIRSTNAME, 
(SELECT SUM(QUANTITY*SALEPRICE) 
FROM PET..SALEITEM SI 
INNER JOIN PET..SALE S ON SI.SALEID = S.SALEID 
WHERE C.CUSTOMERID = S.CUSTOMERID) AS "MERCTOTAL", 
(SELECT SUM(SALEPRICE) 
FROM PET..SALEANIMAL SA 
INNER JOIN PET..SALE S ON SA.SALEID = S.SALEID 
WHERE C.CUSTOMERID = S.CUSTOMERID) AS "ANIMALTOTAL"
FROM PET..CUSTOMER C) Q
ORDER BY (Q.MERCTOTAL+Q.ANIMALTOTAL) DESC
--6
SELECT C.CustomerID, C.LastName, C.FirstName, 
SUM(Si.Quantity*Si.SalePrice)	AS "MayTotal"
FROM PET..Sale S Inner Join PET..Customer C  ON S.CustomerID = C.CustomerID
		Inner Join PET..SaleItem Si ON S.SaleID = Si.SaleID
WHERE MONTH(s.SaleDate) = 5
GROUP BY C.CustomerID, C.LastName, C.FirstName 
HAVING SUM(Si.Quantity*Si.SalePrice) > 100 AND 
C.CUSTOMERID IN (
 SELECT CUSTOMERID 
 FROM PET..SALE S INNER JOIN PET..SALEITEM SI ON SI.SaleID = S.SaleID
 GROUP BY S.CustomerID, MONTH(SALEDATE) HAVING MONTH(SALEDATE) = 10 AND 
 SUM(SALEPRICE*QUANTITY)>50)
--7
SELECT Q.Description, Q.ItemID, Q2.PURCHASED, Q.SOLD, Q2.PURCHASED-Q.SOLD AS "NetIncrease"
FROM(
SELECT M.DESCRIPTION, M.ITEMID, SUM(SI.Quantity) as "SOLD"
FROM PET..SALE S LEFT OUTER JOIN PET..SALEITEM SI ON SI.SALEID = S.SALEID
LEFT OUTER JOIN PET..MERCHANDISE M ON M.ITEMID = SI.ITEMID 
WHERE M.DESCRIPTION = 'Dog Food-Can-Premium' AND S.SALEDATE BETWEEN '2004-01-01' AND '2004-06-01'
GROUP BY M.Description, M.ITEMID
) Q,
(SELECT M.DESCRIPTION, M.ITEMID, SUM(O.QUANTITY) AS "PURCHASED"
FROM PET..MERCHANDISE M
LEFT OUTER JOIN PET..ORDERITEM O ON O.ITEMID = M.ITEMID
LEFT OUTER JOIN PET..MERCHANDISEORDER MO ON MO.PONUMBER = O.PONUMBER
WHERE M.DESCRIPTION = 'Dog Food-Can-Premium' AND MO.OrderDate BETWEEN '2004-01-01' AND '2004-06-01'
GROUP BY M.Description, M.ITEMID) Q2
--8
SELECT distinct M.ITEMID, DESCRIPTION, LISTPRICE
FROM PET..MERCHANDISE M INNER JOIN PET..SALEITEM SI ON M.ITEMID = SI.ItemID
INNER JOIN PET..SALE S ON SI.SaleID = S.SaleID
WHERE LISTPRICE > 50 AND m.itemid not in (select itemid from pet..saleitem si inner join pet..sale s on s.SaleID = si.SaleID where month(saledate) = 7)
--9
SELECT M.ITEMID, M.DESCRIPTION, M.QUANTITYONHAND, O.ITEMID
FROM PET..MERCHANDISE M LEFT OUTER JOIN PET..ORDERITEM O ON O.ITEMID = M.ITEMID
LEFT OUTER JOIN PET..MERCHANDISEORDER MO ON O.PONUMBER = MO.PONUMBER
WHERE M.QUANTITYONHAND > 100 AND (YEAR(MO.ORDERDATE) not in (2004) OR o.itemid IS NULL)
--10
SELECT M.ITEMID, M.DESCRIPTION, M.QUANTITYONHAND, (SELECT DISTINCT O.ITEMID FROM PET..ORDERITEM O INNER JOIN PET..MERCHANDISEORDER MO ON MO.PONumber = O.PONumber WHERE ITEMID=M.ITEMID AND YEAR(MO.ORDERDATE) = 2004) AS "ITEMID"
FROM PET..MERCHANDISE M
WHERE M.QUANTITYONHAND > 100 AND (SELECT DISTINCT O.ITEMID FROM PET..ORDERITEM O INNER JOIN PET..MERCHANDISEORDER MO ON MO.PONumber = O.PONumber WHERE ITEMID=M.ITEMID AND YEAR(MO.ORDERDATE) = 2004) IS NULL
--11
CREATE TABLE CustomerCategory
(
CATEGORY VARCHAR(4) NOT NULL,
LOW INT,
HIGH INT
)
INSERT INTO CUSTOMERCATEGORY (CATEGORY, LOW, HIGH) VALUES ('Weak',0,200), ('Good',200,800), ('Best',800,10000)

select Q.CUSTOMERID, Q.LASTNAME, Q.FIRSTNAME, Q.GRANDTOTAL, (SELECT CATEGORY FROM CUSTOMERCATEGORY WHERE Q.GrandTotal >= LOW AND Q.GrandTotal < HIGH) as "Category" 
from(
SELECT C.CUSTOMERID, C.LastName, C.FirstName, SUM(A.SalePrice)+SUM(I.SalePrice*i.Quantity) AS "GrandTotal"
FROM PET..CUSTOMER C LEFT OUTER JOIN PET..SALE S ON C.CustomerID = S.SaleID
LEFT OUTER JOIN PET..SaleAnimal A ON S.SALEID = A.SaleID
LEFT OUTER JOIN PET..SaleItem I ON S.SaleID = I.SaleID GROUP BY C.CustomerID, C.LastName, C.FirstName) Q
WHERE GrandTotal IS NOT NULL
--12
SELECT DISTINCT S.NAME AS "Supplier Name", 'Animal' as "Order Type", A.OrderDate
FROM PET..SUPPLIER S INNER JOIN PET..ANIMALORDER A ON S.SUPPLIERID = A.SUPPLIERID WHERE MONTH(A.OrderDate) = 6
UNION ALL
SELECT DISTINCT S.NAME AS "Supplier Name", 'Merchandise' as "Order Type", M.OrderDate
FROM PET..SUPPLIER S INNER JOIN PET..MerchandiseOrder M ON S.SUPPLIERID = M.SUPPLIERID WHERE MONTH(M.OrderDate) = 6
ORDER BY s.Name