--Louis Ries
--A9

USE "CIS31026"
GO
IF EXISTS (SELECT * FROM SYS.objects R WHERE NAME = 'A9') DROP TRIGGER "MovieCo"."A9"
GO
CREATE TRIGGER "MovieCo"."A9"
ON "MovieCo"."DETAILRENTAL"
AFTER INSERT, DELETE, UPDATE
AS 
BEGIN
    IF (EXISTS (SELECT * FROM inserted) AND EXISTS (SELECT * FROM deleted))
    BEGIN
        DECLARE MOVIECURSOR CURSOR FOR
        SELECT I.RENT_NUM, I.VID_NUM, I.DETAIL_DUEDATE, I.DETAIL_RETURNDATE,I.DETAIL_DAILYLATEFEE, 
            D.DETAIL_DUEDATE, D.DETAIL_RETURNDATE, D.DETAIL_DAILYLATEFEE
          FROM inserted I INNER JOIN DELETED D ON I.Rent_Num = D.Rent_Num AND I.Vid_Num = D.Vid_Num

        DECLARE @RENT_NUM INT
		DECLARE @VID_NUM INT
        DECLARE @RETURN_DATE_OLD DATETIME
        DECLARE @RETURN_DATE_NEW DATETIME
        DECLARE @DUE_DATE_OLD DATETIME
        DECLARE @DUE_DATE_NEW DATETIME
        DECLARE @DAILY_LATE_FEE_OLD DECIMAL(5,2)
        DECLARE @DAILY_LATE_FEE_NEW DECIMAL(5,2)
        DECLARE @LATE_FEE_PRIOR DECIMAL(5,2)
        DECLARE @LATE_FEE_AFTER DECIMAL(5,2)
        DECLARE @CHANGE DECIMAL (5,2)

        OPEN MOVIECURSOR 
        FETCH NEXT FROM MOVIECURSOR
        INTO @RENT_NUM, @VID_NUM, @DUE_DATE_NEW, @RETURN_DATE_NEW, @DAILY_LATE_FEE_NEW, 
                @DUE_DATE_OLD, @RETURN_DATE_OLD, @DAILY_LATE_FEE_OLD

        WHILE (@@FETCH_STATUS = 0)
        BEGIN
            IF(@RETURN_DATE_OLD > @DUE_DATE_OLD)
                SELECT @LATE_FEE_PRIOR = DATEDIFF(DAY, @DUE_DATE_OLD, @RETURN_DATE_OLD) * @DAILY_LATE_FEE_OLD;
            ELSE
                SELECT @LATE_FEE_PRIOR = 0;
            IF(@RETURN_DATE_NEW > @DUE_DATE_NEW) 
                SELECT @LATE_FEE_AFTER = DATEDIFF(DAY, @DUE_DATE_NEW, @RETURN_DATE_NEW) * @DAILY_LATE_FEE_NEW
            ELSE
                SELECT @LATE_FEE_AFTER = 0
            SELECT @CHANGE = @LATE_FEE_AFTER - @LATE_FEE_PRIOR
            IF(@CHANGE <> 0)
            BEGIN
                DECLARE @MEM_NUM INT;
                SELECT @MEM_NUM = M.Mem_Num
                  FROM RENTAL R 
                  INNER JOIN MEMBERSHIP M ON R.MEM_NUM = M.MEM_NUM AND R.RENT_NUM = @RENT_NUM
				 UPDATE DETAILRENTAL
					SET DETAIL_FEE = DETAIL_FEE + @CHANGE
					WHERE Rent_Num = @RENT_NUM AND VID_NUM = @VID_NUM
				 UPDATE MEMBERSHIP
                   SET Mem_Balance = MEM_BALANCE + @CHANGE
                   WHERE Mem_Num = @MEM_NUM 
            END
            FETCH NEXT FROM MOVIECURSOR
            INTO @RENT_NUM, @VID_NUM, @DUE_DATE_NEW, @RETURN_DATE_NEW, @DAILY_LATE_FEE_NEW, 
                @DUE_DATE_OLD, @RETURN_DATE_OLD, @DAILY_LATE_FEE_OLD
        END
        CLOSE MOVIECURSOR
    END
END
SET IDENTITY_INSERT MOVIECO.DETAILRENTAL ON
SELECT M.MEM_NUM, D.RENT_NUM, D.Vid_Num, D.Detail_DueDate, D.Detail_ReturnDate, D.Detail_DailyLateFee, D.DETAIL_FEE, M.MEM_BALANCE FROM MOVIECO.DETAILRENTAL D INNER JOIN MOVIECO.RENTAL R ON R.Rent_Num = D.Rent_Num INNER JOIN MOVIECO.MEMBERSHIP M ON M.Mem_Num = R.Mem_Num WHERE D.RENT_NUM IN (1006,1007)
UPDATE MOVIECO.DETAILRENTAL SET Detail_DueDate = DETAIL_DUEDATE-3 WHERE RENT_NUM IN (1006,1007)
SELECT M.MEM_NUM, D.RENT_NUM, D.Vid_Num, D.Detail_DueDate, D.Detail_ReturnDate, D.Detail_DailyLateFee, D.DETAIL_FEE, M.MEM_BALANCE FROM MOVIECO.DETAILRENTAL D INNER JOIN MOVIECO.RENTAL R ON R.Rent_Num = D.Rent_Num INNER JOIN MOVIECO.MEMBERSHIP M ON M.Mem_Num = R.Mem_Num WHERE D.RENT_NUM IN (1006,1007)
UPDATE MOVIECO.DETAILRENTAL SET Detail_DueDate = DETAIL_DUEDATE+3 WHERE RENT_NUM IN (1006,1007)
SELECT M.MEM_NUM, D.RENT_NUM, D.Vid_Num, D.Detail_DueDate, D.Detail_ReturnDate, D.Detail_DailyLateFee, D.DETAIL_FEE, M.MEM_BALANCE FROM MOVIECO.DETAILRENTAL D INNER JOIN MOVIECO.RENTAL R ON R.Rent_Num = D.Rent_Num INNER JOIN MOVIECO.MEMBERSHIP M ON M.Mem_Num = R.Mem_Num WHERE D.RENT_NUM IN (1006,1007)
INSERT INTO MOVIECO.DETAILRENTAL (Vid_Num,Rent_Num,Detail_DailyLateFee,Detail_DueDate,Detail_Fee, Detail_ReturnDate) VALUES (34366,1007,3,'2013-03-03',1,'2013-03-04')
UPDATE MOVIECO.DETAILRENTAL SET Detail_DueDate = DETAIL_DUEDATE+3 WHERE RENT_NUM IN (1006,1007)
SELECT M.MEM_NUM, D.RENT_NUM, D.Vid_Num, D.Detail_DueDate, D.Detail_ReturnDate, D.Detail_DailyLateFee, D.DETAIL_FEE, M.MEM_BALANCE FROM MOVIECO.DETAILRENTAL D INNER JOIN MOVIECO.RENTAL R ON R.Rent_Num = D.Rent_Num INNER JOIN MOVIECO.MEMBERSHIP M ON M.Mem_Num = R.Mem_Num WHERE D.RENT_NUM IN (1006,1007)
DELETE FROM MOVIECO.DETAILRENTAL WHERE VID_NUM = 34366 AND RENT_NUM = 1007
SELECT M.MEM_NUM, D.RENT_NUM, D.Vid_Num, D.Detail_DueDate, D.Detail_ReturnDate, D.Detail_DailyLateFee, D.DETAIL_FEE, M.MEM_BALANCE FROM MOVIECO.DETAILRENTAL D INNER JOIN MOVIECO.RENTAL R ON R.Rent_Num = D.Rent_Num INNER JOIN MOVIECO.MEMBERSHIP M ON M.Mem_Num = R.Mem_Num WHERE D.RENT_NUM IN (1006,1007)